package model;

public enum Type {
    INTEGER_LITERAL, REAL_LITERAL, RATIONAL_LITERAL, COMPLEX_LITERAL, STRING_LITERAL,
    KEYWORD, OPERATOR, COMMENT, DELIMITER, IDENTIFIER, INPUT_LINE_SEPARATOR, EOF
}
